environment:
  # [dev | prod]
  type: dev

logger:
  # [info | debug | warn | error]
  level: info

storage:
  # [sql | memory]
  type: memory

server:
  host: 127.0.0.1
  httpPort: 8000
  grpcPort: 9000

db:
  username: postgres
  password: password
  host: host
  port: port
  name: postgres
  sslmode: disable
