version: "3"

services:
  calendar:
    build:
      context: .
      dockerfile: build/calendar/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
  database:
    image: postgres:13.8-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calendar
    volumes:
      - /tmp/database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
